name: weather_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  envied: ^1.3.0
  flutter_dotenv: ^5.1.0
  dio: ^5.9.0
  env_flutter: ^0.1.4
  http: ^1.5.0
  geolocator: ^10.0.0 # Обновляем до последней версии
  geocoding: ^2.1.0
  lottie: ^3.3.2
  intl: ^0.20.2
  firebase_database:
  firebase_core:
  firebase_remote_config:
  location: ^8.0.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  envied_generator: ^1.3.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/rain.json
    - assets/sunny.json
    - assets/nigth.json
    - assets/telt.json
    - assets/thunder.json
    - assets/thunder1.json
    - assets/jello.json
    - assets/cloudy.json
    - assets/cat.json
    - assets/doggy.json
    - assets/yay.json
    - assets/snow.json

    - .env